package types

import (
	"errors"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestRelay_ValidateStruct(t *testing.T) {
	c := require.New(t)

	tests := []struct {
		name  string
		relay Relay
		err   error
	}{
		{
			name: "Success no error relay",
			relay: Relay{
				PoktChainID:              "21",
				EndpointID:               "21",
				SessionKey:               "21",
				ProtocolAppPublicKey:     "21",
				RelaySourceURL:           "pablo.com",
				PoktNodeAddress:          "21",
				PoktNodeDomain:           "pablos.com",
				PoktNodePublicKey:        "aaa",
				RelayStartDatetime:       time.Now(),
				RelayReturnDatetime:      time.Now(),
				RelayRoundtripTime:       1,
				RelayChainMethodIDs:      []string{"get_height"},
				RelayDataSize:            21,
				RelayPortalTripTime:      21,
				RelayNodeTripTime:        21,
				RelayURLIsPublicEndpoint: false,
				PortalRegionName:         "La Colombia",
				IsAltruistRelay:          false,
				IsUserRelay:              false,
				RequestID:                "21",
				PoktTxID:                 "21",
			},
			err: nil,
		},
		{
			name: "Success no error relay",
			relay: Relay{
				PoktChainID:              "21",
				EndpointID:               "21",
				SessionKey:               "21",
				ProtocolAppPublicKey:     "21",
				RelaySourceURL:           "pablo.com",
				PoktNodeAddress:          "21",
				PoktNodeDomain:           "pablos.com",
				PoktNodePublicKey:        "aaa",
				RelayStartDatetime:       time.Now(),
				RelayReturnDatetime:      time.Now(),
				IsError:                  true,
				ErrorCode:                21,
				ErrorName:                "favorite number",
				ErrorMessage:             "just Pablo can use it",
				ErrorType:                "chain_check",
				ErrorSource:              "internal",
				RelayRoundtripTime:       1,
				RelayChainMethodIDs:      []string{"get_height"},
				RelayDataSize:            21,
				RelayPortalTripTime:      21,
				RelayNodeTripTime:        21,
				RelayURLIsPublicEndpoint: false,
				PortalRegionName:         "La Colombia",
				IsAltruistRelay:          false,
				IsUserRelay:              false,
				RequestID:                "21",
				PoktTxID:                 "21",
			},
			err: nil,
		},
		{
			name: "Failure no erro relay with error fields",
			relay: Relay{
				PoktChainID:              "21",
				EndpointID:               "21",
				SessionKey:               "21",
				ProtocolAppPublicKey:     "21",
				RelaySourceURL:           "pablo.com",
				PoktNodeAddress:          "21",
				PoktNodeDomain:           "pablos.com",
				PoktNodePublicKey:        "aaa",
				RelayStartDatetime:       time.Now(),
				RelayReturnDatetime:      time.Now(),
				IsError:                  false,
				ErrorCode:                21,
				ErrorName:                "favorite number",
				ErrorMessage:             "just Pablo can use it",
				ErrorType:                "chain_check",
				ErrorSource:              "internal",
				RelayRoundtripTime:       1,
				RelayChainMethodIDs:      []string{"get_height"},
				RelayDataSize:            21,
				RelayPortalTripTime:      21,
				RelayNodeTripTime:        21,
				RelayURLIsPublicEndpoint: false,
				PortalRegionName:         "La Colombia",
				IsAltruistRelay:          false,
				IsUserRelay:              false,
				RequestID:                "21",
				PoktTxID:                 "21",
			},
			err: errors.New("ErrorCode should not be set"),
		},
		{
			name: "Failure invalid error type",
			relay: Relay{
				PoktChainID:              "21",
				EndpointID:               "21",
				SessionKey:               "21",
				ProtocolAppPublicKey:     "21",
				RelaySourceURL:           "pablo.com",
				PoktNodeAddress:          "21",
				PoktNodeDomain:           "pablos.com",
				PoktNodePublicKey:        "aaa",
				RelayStartDatetime:       time.Now(),
				RelayReturnDatetime:      time.Now(),
				IsError:                  true,
				ErrorCode:                21,
				ErrorName:                "favorite number",
				ErrorMessage:             "just Pablo can use it",
				ErrorType:                "chain_check",
				ErrorSource:              "pablito",
				RelayRoundtripTime:       1,
				RelayChainMethodIDs:      []string{"get_height"},
				RelayDataSize:            21,
				RelayPortalTripTime:      21,
				RelayNodeTripTime:        21,
				RelayURLIsPublicEndpoint: false,
				PortalRegionName:         "La Colombia",
				IsAltruistRelay:          false,
				IsUserRelay:              false,
				RequestID:                "21",
				PoktTxID:                 "21",
			},
			err: errors.New("ErrorSource is not valid"),
		},
		{
			name: "Failure error relay without error fields",
			relay: Relay{
				PoktChainID:              "21",
				EndpointID:               "21",
				SessionKey:               "21",
				ProtocolAppPublicKey:     "21",
				RelaySourceURL:           "pablo.com",
				PoktNodeAddress:          "21",
				PoktNodeDomain:           "pablos.com",
				PoktNodePublicKey:        "aaa",
				RelayStartDatetime:       time.Now(),
				RelayReturnDatetime:      time.Now(),
				IsError:                  true,
				ErrorName:                "favorite number",
				ErrorMessage:             "just Pablo can use it",
				ErrorType:                "pablito",
				ErrorSource:              "internal",
				RelayRoundtripTime:       1,
				RelayChainMethodIDs:      []string{"get_height"},
				RelayDataSize:            21,
				RelayPortalTripTime:      21,
				RelayNodeTripTime:        21,
				RelayURLIsPublicEndpoint: false,
				PortalRegionName:         "La Colombia",
				IsAltruistRelay:          false,
				IsUserRelay:              false,
				RequestID:                "21",
				PoktTxID:                 "21",
			},
			err: errors.New("ErrorCode is not set"),
		},
		{
			name: "Failure not set field",
			relay: Relay{
				EndpointID:               "21",
				SessionKey:               "21",
				ProtocolAppPublicKey:     "21",
				RelaySourceURL:           "pablo.com",
				PoktNodeAddress:          "21",
				PoktNodeDomain:           "pablos.com",
				PoktNodePublicKey:        "aaa",
				RelayStartDatetime:       time.Now(),
				RelayReturnDatetime:      time.Now(),
				RelayRoundtripTime:       1,
				RelayChainMethodIDs:      []string{"get_height"},
				RelayDataSize:            21,
				RelayPortalTripTime:      21,
				RelayNodeTripTime:        21,
				RelayURLIsPublicEndpoint: false,
				PortalRegionName:         "La Colombia",
				IsAltruistRelay:          false,
				IsUserRelay:              false,
				RequestID:                "21",
				PoktTxID:                 "21",
			},
			err: errors.New("PoktChainID is not set"),
		},
		{
			name: "Failure set field should not be set",
			relay: Relay{
				PoktChainID:              "21",
				EndpointID:               "21",
				SessionKey:               "21",
				ProtocolAppPublicKey:     "21",
				RelaySourceURL:           "pablo.com",
				PoktNodeAddress:          "21",
				PoktNodeDomain:           "pablos.com",
				PoktNodePublicKey:        "aaa",
				RelayStartDatetime:       time.Now(),
				RelayReturnDatetime:      time.Now(),
				RelayRoundtripTime:       1,
				RelayChainMethodIDs:      []string{"get_height"},
				RelayDataSize:            21,
				RelayPortalTripTime:      21,
				RelayNodeTripTime:        21,
				RelayURLIsPublicEndpoint: false,
				PortalRegionName:         "La Colombia",
				IsAltruistRelay:          false,
				IsUserRelay:              false,
				RequestID:                "21",
				PoktTxID:                 "21",
				Session:                  PocketSession{SessionKey: "21"},
			},
			err: errors.New("Session should not be set"),
		},
	}

	for _, tt := range tests {
		c.Equal(tt.err, tt.relay.Validate())
	}
}
