// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package postgresdriver

import (
	"time"
)

type Error struct {
	ErrorID          int32  `json:"errorID"`
	ErrorCode        int32  `json:"errorCode"`
	ErrorName        string `json:"errorName"`
	ErrorDescription string `json:"errorDescription"`
}

type PocketSession struct {
	PocketSessionID       int32  `json:"pocketSessionID"`
	SessionKey            string `json:"sessionKey"`
	SessionHeight         int32  `json:"sessionHeight"`
	ProtocolApplicationID int32  `json:"protocolApplicationID"`
}

type PortalRegion struct {
	PortalRegionID   int32  `json:"portalRegionID"`
	PortalRegionName string `json:"portalRegionName"`
}

type Relay struct {
	RelayID                  int64     `json:"relayID"`
	ChainID                  int32     `json:"chainID"`
	EndpointID               int32     `json:"endpointID"`
	PocketSessionID          int32     `json:"pocketSessionID"`
	PoktNodeAddress          string    `json:"poktNodeAddress"`
	RelayStartDatetime       time.Time `json:"relayStartDatetime"`
	RelayReturnDatetime      time.Time `json:"relayReturnDatetime"`
	IsError                  bool      `json:"isError"`
	ErrorID                  int32     `json:"errorID"`
	RelayRoundtripTime       int32     `json:"relayRoundtripTime"`
	RelayChainMethodID       int32     `json:"relayChainMethodID"`
	RelayDataSize            int32     `json:"relayDataSize"`
	RelayPortalTripTime      int32     `json:"relayPortalTripTime"`
	RelayNodeTripTime        int32     `json:"relayNodeTripTime"`
	RelayUrlIsPublicEndpoint bool      `json:"relayUrlIsPublicEndpoint"`
	PortalOriginRegionID     int32     `json:"portalOriginRegionID"`
	IsAltruistRelay          bool      `json:"isAltruistRelay"`
}
